name: jest-coverage
run-name: ${{ github.actor }} 
on: ["push", "pull_request"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: npm install, make jest-coverage
      run: |
        npm install
        npm run test:coverage

    - name: Coveralls
      uses: coverallsapp/github-action@v2
